### ISSUE TITLE
Under Maintenance

### ISSUE THREAD

**Issue by darkmaniac7** [TDarkShadow/vivanewvegas-wabbajack#10]
Hey there, I know in the GitHub mainpage it said that WabbaJack would be updated if this happens but it's been a bit over two weeks and I was hoping to install this, is there a way to bypass or override the WabbaJack "under Maintenance" gate?

**Comment by TDarkShadow** [comment]
My apologies @darkmaniac7 
This has now been fixed as of v1.5.0
