### ISSUE TITLE
Wabbajack 'Under Maintenance'?

### ISSUE THREAD

**Issue by BlueRasputin** [TDarkShadow/vivanewvegas-wabbajack#12]
Wabbajack currently shows VNV as 'Under maintenance' and under the reasoning, it says that some of the mods within are in need of an update to the newest version. Will this be resolved soon? Thanks!

**Comment by peskovsky** [comment]
And using the latest release from github (the one of May 12) results into errors while downloading some mods:

> 1005,71 - Unable to download WMIM - JSUE Patch.7z (HTTPDownloader+State|https://github.com/VivaNewVegas/Viva-New-Vegas-Patch-Emporium/raw/8b671138c7e567340a6a01ea9e3d18d1c8928015/WMIM%20-%20JSUE%20Patch.7z)
> 1005,71 - Unable to download Mojave Raiders Tweaks.7z (HTTPDownloader+State|https://github.com/VivaNewVegas/Viva-New-Vegas-Patch-Emporium/raw/8b671138c7e567340a6a01ea9e3d18d1c8928015/Mojave%20Raiders%20Tweaks.7z)
> 1005,71 - Unable to download Real Recoil Tweaks.7z (HTTPDownloader+State|https://github.com/VivaNewVegas/Viva-New-Vegas-Patch-Emporium/raw/8b671138c7e567340a6a01ea9e3d18d1c8928015/Real%20Recoil%20Tweaks.7z)
> 1005,71 - Unable to download Uncut Wasteland Tweaks.7z (HTTPDownloader+State|https://github.com/VivaNewVegas/Viva-New-Vegas-Patch-Emporium/raw/1a9d0e0aa16d5abf6130ddf250c4aefb85b0a7cf/Uncut%20Wasteland%20Tweaks.7z)
> 1005,71 - Unable to download Vanilla_UI_Plus_New_Vegas_8.95.7z (ModDBDownloader+State|https://www.moddb.com/downloads/start/128019?referer=https%3A%2F%2Fvivanewvegas.github.io%2F)
> 1005,71 - Unable to download WMIM ESP Replacer.7z (HTTPDownloader+State|https://github.com/VivaNewVegas/Viva-New-Vegas-Patch-Emporium/raw/8b671138c7e567340a6a01ea9e3d18d1c8928015/WMIM%20ESP%20Replacer.7z)
> 1005,71 - Unable to download Just Assorted Mods Custom INI.7z (HTTPDownloader+State|https://github.com/VivaNewVegas/Viva-New-Vegas-Patch-Emporium/raw/772d653d5119998d2869e173916bb755f6286890/Just%20Assorted%20Mods%20Custom%20INI.7z)
> 1005,71 - Unable to download JIP LN Overhauls INI.7z (HTTPDownloader+State|https://github.com/VivaNewVegas/Viva-New-Vegas-Patch-Emporium/raw/106649ea65e4052429465098a9fb2cd47dbbd652/JIP%20LN%20Overhauls%20INI.7z)
> 1005,71 - Unable to download lStewieAl's Tweaks Custom INI.7z (HTTPDownloader+State|https://github.com/VivaNewVegas/Viva-New-Vegas-Patch-Emporium/raw/149b740024760c1d5faf28b61351f11e1c578d5d/lStewieAl's%20Tweaks%20Custom%20INI.7z)
> 1005,71 - Unable to download Stewie's Tweaks Overhauls INI.7z (HTTPDownloader+State|https://github.com/VivaNewVegas/Viva-New-Vegas-Patch-Emporium/raw/149b740024760c1d5faf28b61351f11e1c578d5d/Stewie's%20Tweaks%20Overhauls%20INI.7z)
> 1005,72 - Cannot continue, was unable to download one or more archives

**Comment by peskovsky** [comment]
The recent release ("Partial VNV Setup - 18 August 2022") fixed the problems. Now the installation works properly as well as the game afterwards.
Thank you so much for you work, @TDarkShadow!

**Comment by TDarkShadow** [comment]
Thanks for reminding, forgot to close these issues.

@BlueRasputin this is now fixed as per v1.5.0
