### ISSUE TITLE
Issue with Uncut Wasteland 

### ISSUE THREAD

**Issue by steveyminecraft** [TDarkShadow/vivanewvegas-wabbajack#17]
I am running into this error at present. I can download the mod manually however by following the link in my broswer

```
00:02:42.106 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Downloading files
00:02:42.106 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading Uncut Wasteland.7z
00:02:42.606 [FATAL] (Wabbajack.Downloaders.DownloadDispatcher) While finding mirror for 3EAe9MiX0D0=|System.NullReferenceException: Object reference not set to an instance of an object.
   at Wabbajack.Downloaders.WabbajackCDNDownloader.Download(Archive archive, WabbajackCDN state, AbsolutePath destination, IJob job, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.WabbajackCDN\WabbajackCDNDownloader.cs:line 83
   at Wabbajack.Downloaders.WabbajackCDNDownloader.Download(Archive archive, WabbajackCDN state, AbsolutePath destination, IJob job, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.WabbajackCDN\WabbajackCDNDownloader.cs:line 121
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 102
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 48
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadFromMirror(Archive archive, AbsolutePath destination, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 219
00:02:42.606 [ERROR] (Wabbajack.Installer.StandardInstaller) Downloaded hash AAAAAAAAAAA= does not match expected hash: 3EAe9MiX0D0=
00:02:42.606 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:02:42.606 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:02:42.617 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:02:42.617 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:02:42.617 [INFO] (Wabbajack.Installer.StandardInstaller) Found 535 total files, 74 matching filesize
00:02:42.617 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Uncut Wasteland.7z (HTTPDownloader+State|https://github.com/VivaNewVegas/vivanewvegas.github.io/raw/master/files/Uncut Wasteland.7z)
00:02:42.617 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives
```

**Comment by R2162** [comment]
[Wabbajack.00.log](https://github.com/TDarkShadow/vivanewvegas-wabbajack/files/10079406/Wabbajack.00.log)
I've had the exact same issue, and even downloading the file manually and placing it in the downloads folder doesn't fix the issue unfortunately.

**Comment by arkaus** [comment]
I'm encountering the same problem.

**Comment by thoughtwrangler** [comment]
I experienced the same. 
Here's the log file from my latest attempt. It may be worth noting, that this attempt was after the first one, in which it had already grabbed the files from Nexus, so this attempt skipped all that.

17:16:58.477 [INFO] (Wabbajack.InstallerVM) Preparing HttpDownloader
17:16:58.477 [INFO] (Wabbajack.InstallerVM) Preparing NexusDownloader
17:16:58.479 [INFO] (Wabbajack.InstallerVM) Preparing ModDBDownloader
17:16:58.479 [INFO] (Wabbajack.InstallerVM) Preparing GameFileDownloader
17:16:58.536 [INFO] (Wabbajack.Installer.StandardInstaller) Installing: Viva New Vegas - 0.0.1.0
17:16:59.113 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Configuring Installer
17:16:59.113 [INFO] (Wabbajack.Installer.StandardInstaller) Configuring Processor
17:16:59.113 [INFO] (Wabbajack.Installer.StandardInstaller) Install Folder: C:\VivaNewVegas
17:16:59.113 [INFO] (Wabbajack.Installer.StandardInstaller) Downloads Folder: C:\VivaNewVegas\downloads
17:16:59.113 [INFO] (Wabbajack.Installer.StandardInstaller) Game Folder: C:\GOG\Games\Fallout New Vegas
17:16:59.113 [INFO] (Wabbajack.Installer.StandardInstaller) Wabbajack Folder: C:\Wabbajack\3.0.4.1
17:16:59.113 [INFO] (Wabbajack.Installer.StandardInstaller) Optimizing ModList directives
17:16:59.232 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Looking for files to delete
17:16:59.242 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Cleaning empty folders
17:16:59.310 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Looking for unmodified files
17:16:59.341 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Updating ModList
17:16:59.341 [INFO] (Wabbajack.Installer.StandardInstaller) Optimized 7675 directives to 7675 required
17:16:59.350 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
17:16:59.350 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
17:16:59.371 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
17:16:59.418 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
17:16:59.418 [INFO] (Wabbajack.Installer.StandardInstaller) Found 458 total files, 74 matching filesize
17:16:59.465 [INFO] (Wabbajack.Installer.StandardInstaller) Missing 1 archives
17:16:59.465 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading validation data
17:17:00.039 [INFO] (Wabbajack.Installer.StandardInstaller) Validating Archives
17:17:00.039 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading missing archives
17:17:00.039 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading 1 archives
17:17:00.039 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Downloading files
17:17:00.039 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading Uncut Wasteland.7z
17:17:02.039 [FATAL] (Wabbajack.Downloaders.DownloadDispatcher) While finding mirror for 3EAe9MiX0D0=|System.NullReferenceException: Object reference not set to an instance of an object.
   at Wabbajack.Downloaders.WabbajackCDNDownloader.Download(Archive archive, WabbajackCDN state, AbsolutePath destination, IJob job, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.WabbajackCDN\WabbajackCDNDownloader.cs:line 83
   at Wabbajack.Downloaders.WabbajackCDNDownloader.Download(Archive archive, WabbajackCDN state, AbsolutePath destination, IJob job, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.WabbajackCDN\WabbajackCDNDownloader.cs:line 121
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 104
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 49
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadFromMirror(Archive archive, AbsolutePath destination, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 219
17:17:02.039 [ERROR] (Wabbajack.Installer.StandardInstaller) Downloaded hash AAAAAAAAAAA= does not match expected hash: 3EAe9MiX0D0=
17:17:02.039 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
17:17:02.039 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
17:17:02.062 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
17:17:02.093 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
17:17:02.093 [INFO] (Wabbajack.Installer.StandardInstaller) Found 458 total files, 74 matching filesize
17:17:02.154 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Uncut Wasteland.7z (HTTPDownloader+State|https://github.com/VivaNewVegas/vivanewvegas.github.io/raw/master/files/Uncut Wasteland.7z)
17:17:02.154 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives

I went to the directory being pointed to (https://github.com/VivaNewVegas/vivanewvegas.github.io/raw/master/files/) 
and noticed that the links for the files listed there are formatted as such: "https://github.com/VivaNewVegas/vivanewvegas.github.io/blob/master/files/Uncut%20Wasteland.7z". 
"https://github.com/VivaNewVegas/vivanewvegas.github.io/blob/master/files/Real%20Recoil%20Tweaks.7z"

I'm a complete newb, so I may be way out of my depth here. But could the missing %20 be a possible issue when the Wabbajack download list is parsing the URL? (for all I know this could be totally normal and it may be built to resolve it internally.) Or could there be a discrepancy between the "raw/master/files" and "blob/master/files" sections of the filepath? (again, this may be perfectly normal, I don't know.)

If there's any further info or context I can provide, including earlier/fresh log files, let me know.

**Comment by Lukaboot** [comment]
nice support

**Comment by tmagnussen** [comment]
It seems a new version of Uncut Wastelands.7z was uploaded to Github on Nov 13, 2022. Maybe that's the problem so the checksum check now fails?

**Comment by tmagnussen** [comment]
Maybe you could try to download the previous version from here and put it in the download folder:
https://github.com/VivaNewVegas/vivanewvegas.github.io/blob/5c856d8584d6f1bf0d7606486cc2925d74acffea/files/Uncut%20Wasteland.7z
Update: I can confirm that manually copying "Uncut Wastelands.7z" from above location and placing it in the "Resource Download Location" will fix the problem.

Update 2: I don't know if I did anything wrong during the installation but I also had to download and install "New Vegas Heap Replacer" manually - https://www.nexusmods.com/newvegas/mods/69779?tab=files

**Comment by R2162** [comment]
> Update: I can confirm that manually copying "Uncut Wastelands.7z" from above location and placing it in the "Resource Download Location" will fix the problem.

It worked for me as well, though i didn't need to get NVHR manually
